server:
  port: 10010
spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-file-size: 1024MB
eureka:
  client:
    service-url:
      defaultZone: http://112.74.162.78:10086/eureka

zuul:
  prefix: /scm/api
  routes:
    scm-human-service: /human/**
    upload-service: /file/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 35000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0



