server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://112.74.162.78:10086/eureka
    register-with-eureka: false
    fetch-registry: false